# Generated by Django 5.2.16 on 2026-07-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('briefing', models.TextField(blank=True, help_text='Tom, público, o que evitar, exemplos de temas.', verbose_name='Briefing do nicho')),
                ('keywords', models.TextField(blank=True, help_text='Uma por linha. Usadas na pesquisa YouTube e nas sugestões.', verbose_name='Keywords de pesquisa')),
                ('default_voice', models.CharField(blank=True, help_text='Ex.: pt-BR-FranciscaNeural-Female', max_length=120, verbose_name='Voz TTS padrão')),
                ('default_language', models.CharField(default='pt-BR', max_length=20, verbose_name='Idioma do roteiro')),
                ('default_aspect', models.CharField(choices=[('9:16', 'Short 9:16'), ('16:9', 'Landscape 16:9'), ('1:1', 'Square 1:1')], default='9:16', max_length=10, verbose_name='Aspecto padrão')),
                ('default_video_source', models.CharField(default='pexels', help_text='pexels | pixabay | coverr | local', max_length=20, verbose_name='Fonte de material (Create)')),
                ('paragraph_number', models.PositiveSmallIntegerField(default=1, help_text='1–3 para short; 5–10 para vídeo mais longo.', verbose_name='Parágrafos do roteiro')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nicho',
                'verbose_name_plural': 'Nichos',
                'ordering': ['name'],
            },
        ),
    ]
