# Generated by Django 5.2.16 on 2026-07-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niche',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='niches.niche', verbose_name='Nicho pai (subnicho)'),
        ),
    ]
