# Generated by Django 5.2.16 on 2026-07-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('niches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex.: YT Finanças BR, TikTok Curiosidades 2', max_length=120, verbose_name='Nome amigável')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram Reels'), ('facebook', 'Facebook'), ('kwai', 'Kwai')], db_index=True, max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='YouTube channelId, IG business id, Page id, @handle, etc.', max_length=128, verbose_name='ID externo (canal/página/@)')),
                ('username', models.CharField(blank=True, max_length=128, verbose_name='Username / handle')),
                ('auth_mode', models.CharField(choices=[('oauth', 'OAuth'), ('token', 'Access token / API key'), ('upload_post', 'Gateway Upload-Post'), ('manual', 'Manual (sem API)')], default='oauth', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('connected', 'Conectada'), ('error', 'Erro'), ('disabled', 'Desativada')], db_index=True, default='draft', max_length=20)),
                ('credentials_json', models.TextField(blank=True, help_text='Tokens OAuth, access_token, refresh_token, upload_post user, etc. Não versionar.', verbose_name='Credenciais (JSON)')),
                ('default_privacy', models.CharField(blank=True, default='private', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to='niches.niche', verbose_name='Nicho (opcional)')),
            ],
            options={
                'verbose_name': 'Conta social',
                'verbose_name_plural': 'Contas sociais',
                'ordering': ['platform', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublishTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('ready', 'Pronto'), ('uploading', 'Enviando'), ('published', 'Publicado'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], db_index=True, default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Separadas por vírgula', max_length=500)),
                ('hashtags', models.CharField(blank=True, max_length=500)),
                ('privacy', models.CharField(blank=True, max_length=40)),
                ('language', models.CharField(blank=True, default='pt-BR', max_length=20)),
                ('category_id', models.CharField(blank=True, max_length=20)),
                ('made_for_kids', models.BooleanField(default=False)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('extra_json', models.JSONField(blank=True, default=dict, help_text='Campos extras por plataforma (cover_time_ms, share_to_feed, etc.)')),
                ('remote_id', models.CharField(blank=True, max_length=128, verbose_name='ID remoto do post/vídeo')),
                ('remote_url', models.URLField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_targets', to='jobs.job')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publish_targets', to='publishing.socialaccount')),
            ],
            options={
                'verbose_name': 'Destino de publicação',
                'verbose_name_plural': 'Destinos de publicação',
            },
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('platform', 'name'), name='uniq_social_account_platform_name'),
        ),
        migrations.AlterUniqueTogether(
            name='publishtarget',
            unique_together={('job', 'account')},
        ),
    ]
