# Generated by Django 5.2.16 on 2026-07-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('summary_pt', models.TextField(blank=True)),
                ('topics_json', models.JSONField(blank=True, default=list)),
                ('candidates_json', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_runs', to='niches.niche')),
            ],
            options={
                'verbose_name': 'Execução de trends',
                'verbose_name_plural': 'Execuções de trends',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('hooks', models.TextField(blank=True)),
                ('cta', models.TextField(blank=True)),
                ('hashtags', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('ai_score', models.FloatField(blank=True, help_text="0–100 probabilidade de IA (quanto maior, mais 'IA')", null=True)),
                ('ai_status', models.CharField(choices=[('unknown', 'Desconhecido'), ('pass', 'Humano / OK'), ('review', 'Revisar'), ('regen', 'Regenerar (muito IA)'), ('skipped', 'Detector não configurado')], default='unknown', max_length=20)),
                ('ai_raw', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_drafts', to='niches.niche')),
                ('trend_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='ui.trendrun')),
            ],
            options={
                'verbose_name': 'Rascunho de roteiro',
                'verbose_name_plural': 'Rascunhos de roteiro',
                'ordering': ['-updated_at'],
            },
        ),
    ]
