# Generated by Django 5.2.16 on 2026-07-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex.: Moonshot produção, OpenAI barata', max_length=120, verbose_name='Nome amigável')),
                ('provider', models.CharField(help_text='moonshot, openai, gemini, deepseek, …', max_length=40, verbose_name='Provider')),
                ('api_key', models.TextField(verbose_name='API key')),
                ('base_url', models.CharField(blank=True, max_length=300)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Usada quando nenhuma IA for escolhida na pesquisa.', verbose_name='Padrão para Trends')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial de IA',
                'verbose_name_plural': 'Credenciais de IA',
                'ordering': ['-is_default', 'provider', 'name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'name'), name='uniq_llm_credential_provider_name')],
            },
        ),
        migrations.AddField(
            model_name='trendrun',
            name='llm_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend_runs', to='ui.llmcredential', verbose_name='IA usada'),
        ),
    ]
