# Generated by Django 5.2.16 on 2026-07-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niches', '0002_niche_parent'),
        ('ui', '0002_llmcredential_trendrun_llm_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='NicheDiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('root', 'Nichos principais'), ('sub', 'Subnichos')], default='root', max_length=10)),
                ('summary_pt', models.TextField(blank=True)),
                ('suggestions_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niche_discoveries', to='ui.llmcredential')),
                ('parent_niche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovery_runs', to='niches.niche')),
            ],
            options={
                'verbose_name': 'Descoberta de nichos',
                'verbose_name_plural': 'Descobertas de nichos',
                'ordering': ['-created_at'],
            },
        ),
    ]
