# Generated by Django 5.2.16 on 2026-07-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_nichediscoveryrun_signals_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeDataApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(blank=True, verbose_name='YouTube API key')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Data API key',
                'verbose_name_plural': 'YouTube Data API keys',
            },
        ),
    ]
