# Generated by Django 5.2.16 on 2026-07-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_youtube_data_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='nichediscoveryrun',
            name='video_format',
            field=models.CharField(blank=True, default='dark', help_text='dark | face | hybrid | screen | any — filtro da descoberta.', max_length=20, verbose_name='Formato de vídeo'),
        ),
    ]
