# Generated by Django 5.x for VideoPlan

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("niches", "0002_niche_parent"),
        ("ui", "0006_niche_discovery_video_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_format",
                    models.CharField(
                        blank=True,
                        default="dark",
                        max_length=20,
                        verbose_name="Formato de vídeo",
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=300, verbose_name="Tema")),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Título")),
                ("script_body", models.TextField(blank=True, verbose_name="Roteiro")),
                (
                    "voice_name",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: pt-BR-FranciscaNeural-Female",
                        max_length=120,
                        verbose_name="Voz TTS",
                    ),
                ),
                ("voice_notes", models.TextField(blank=True, verbose_name="Notas da voz")),
                ("assets_json", models.JSONField(blank=True, default=list)),
                ("dub_suggestions_json", models.JSONField(blank=True, default=list)),
                ("plan_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Rascunho"), ("ready", "Pronto")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "llm_credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_plans",
                        to="ui.llmcredential",
                        verbose_name="IA usada",
                    ),
                ),
                (
                    "niche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_plans",
                        to="niches.niche",
                    ),
                ),
                (
                    "script_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_plans",
                        to="ui.scriptdraft",
                        verbose_name="Roteiro vinculado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de vídeo",
                "verbose_name_plural": "Planos de vídeo",
                "ordering": ["-updated_at"],
            },
        ),
    ]
