# Generated by Django 5.2.16 on 2026-07-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary_pt', models.TextField(blank=True)),
                ('suggestions_json', models.JSONField(blank=True, default=dict)),
                ('candidates_json', models.JSONField(blank=True, default=list)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_snapshots', to='niches.niche')),
            ],
            options={
                'verbose_name': 'Snapshot de pesquisa',
                'verbose_name_plural': 'Snapshots de pesquisa',
                'ordering': ['-created_at'],
            },
        ),
    ]
