# Generated by Django 5.2.16 on 2026-07-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título do canal')),
                ('channel_id', models.CharField(blank=True, max_length=64, verbose_name='YouTube Channel ID')),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connected', 'Conectado'), ('error', 'Erro')], default='disconnected', max_length=20)),
                ('token_json', models.TextField(blank=True, help_text='Preenchido automaticamente após o OAuth.', verbose_name='OAuth token (JSON)')),
                ('last_error', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_channel', to='niches.niche', verbose_name='Nicho')),
            ],
            options={
                'verbose_name': 'Canal YouTube',
                'verbose_name_plural': 'Canais YouTube',
            },
        ),
    ]
