# Generated by Django 5.2.16 on 2026-07-22 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('niches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_type', models.CharField(choices=[('create', 'Create (stock + TTS)'), ('clip', 'Clip (cortes YouTube)'), ('dub', 'Dub (EN → PT)'), ('research', 'Pesquisa de nicho')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('queued', 'Na fila'), ('running', 'Executando'), ('awaiting_review', 'Aguardando revisão'), ('approved', 'Aprovado'), ('uploading', 'Enviando ao YouTube'), ('published', 'Publicado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=30)),
                ('subject', models.CharField(blank=True, help_text='Create: tema do short. Clip/Dub: assunto do corte ou dublagem.', max_length=300, verbose_name='Tema / assunto')),
                ('source_url', models.URLField(blank=True, help_text='Link do YouTube ou arquivo remoto.', verbose_name='URL de origem (Clip/Dub)')),
                ('cut_topic', models.CharField(blank=True, help_text="Ex.: 'momento engraçado', 'dica de finanças'.", max_length=300, verbose_name='Assunto do corte (Clip)')),
                ('target_duration_sec', models.PositiveIntegerField(default=45, verbose_name='Duração alvo do corte (s)')),
                ('script_override', models.TextField(blank=True, verbose_name='Roteiro manual (opcional)')),
                ('output_title', models.CharField(blank=True, max_length=100, verbose_name='Título YouTube')),
                ('output_description', models.TextField(blank=True, verbose_name='Descrição YouTube')),
                ('privacy_status', models.CharField(default='private', help_text='private | unlisted | public', max_length=20)),
                ('engine_task_id', models.CharField(blank=True, max_length=64)),
                ('work_dir', models.CharField(blank=True, max_length=500)),
                ('output_video', models.CharField(blank=True, max_length=500)),
                ('youtube_video_id', models.CharField(blank=True, max_length=64)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='channels.youtubechannel')),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='niches.niche')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
